### PR TITLE
Windows instructions

### PR DESCRIPTION
**Pull request by cgranade**
After some debugging of a Windows installation, @csferrie and I found a simple recipe for installing using Anaconda 2.2.0 that seems to work rather reliably, so I thought I'd suggest it for addition to the docs.

### CODE REVIEW

**Comment by cgranade** [comment]
My apologies, I seem to have accidentally included something from my previous local feature branch when I made this PR. Mental note: checkout master, *then* branch.

**Comment by ajgpitch** [comment]
As Anaconda seems to be currently the preferred solution on Windows platforms, should we put this ahead of Pythonxy on the instructions?  Do we need to specify a particular version, or should be just say (tested on 2.2.0)?

**Comment by cgranade** [comment]
That seems like a good idea. I'd love it if I could recommend Python(x, y) over Anaconda, but especially on 64-bit Windows and recent versions of OS X, Anaconda is just much easier to work with. As for versions, I've mostly been working with 2.2.0 and 2.3.0, but I suspect it should be mostly independent of version. I think noting where we've tested is useful, though. I'll make these changes soon.

**Comment by cgranade** [comment]
I wanted to revisit this, as users are still posting in the Google Groups page and contacting me personally to get QuTiP working on Windows. This seems to be nontrivial, and I would like to get instructions that work easily, whether with Anaconda or with something else, posted to the official guide ASAP.

**Comment by ajgpitch** [comment]
Yes, I have found Anaconda to work in all cases where I have had to help
people getting QuTiP working on Windows. The only issue I had was on the
win7 virtual machine I tried as a test, which I never managed to resolve.

I would be great to have a more reliable method of install up there live.
There was some mention of trying to make pre-packaged binaries for Windows.
It seems like a really good idea, but perhaps a lot of work?

**Comment by cgranade** [comment]
I think getting an Anaconda Binstar recipe up and running would help a lot
for this kind of issue, as then installing on Windows/Anaconda would be as
simple as a pip-based install. That said that's also a bit farther out, and
I think getting up instructions that work most of the time would be a good
step.

**Comment by ajgpitch** [comment]
Should we publish this update, as it is an improvement on the current site, even if not perfect?

**Comment by cgranade** [comment]
I think that makes sense, given that the Windows install is currently a
point of pain.

**Pull request merged**
