### PR TITLE
Build4.4

### PR DESCRIPTION
**Pull request by Ericgig**
Update for Qutip 4.4
@nathanshammah @ajgpitch could you help me with the changelog?

### CODE REVIEW

**Comment by nathanshammah** [comment]
The following could be a draft for the changelog.rst.txt to be added to the /sources/ folder in the documentation. 

.. QuTiP 
   Copyright (C) 2011-2018, Paul D. Nation, Robert J. Johansson, Chris Granade, Arne Grimsmo & Alexander Pitchford
   Copyright (C) 2018-2019, QuTiP Development Team: Alexander Pitchford, Shahnawaz Ahmed, Éric Giguère, Nathan Shammah, Neill Lambert

.. _changelog:

**********
Change Log
**********

Version 4.4.0 (July 1, 2019)
++++++++++++++++++++++++++++++

Improvements
------------
- **MAJOR FEATURE**: Added methods and techniques to the stochastic solvers (**by Éric Giguère**) which allows to use a much broader set of solvers and much more efficiently.

- **MAJOR FEATURE**: Added the QObjEvo class and methods(**by Éric Giguère**), which is used behind the scenes by the dynamical solvers, making code more efficient and tidier.

- **MAJOR FEATURE**: Added a new version of mcsolve (**by Eric Giguere**), which allows for time-dependent collapse operators.

- mcsolve is now orders of magnitude faster when e_ops are not given, and with similar performance or much faster when e_ops are given.


- QIP module: added the possibility for user-defined gates, added the possibility to remove or add gates in any point of an already built circuit, added the `molmer_sorensen` gate, and fixed some bugs (**by Boxi Li**)


- added the quantum Hellinger distance to `qutip.metrics` (**by Wojciech Rzadkowski**) 

- implemented possibility of choosing random seed (**by Marek**)

- added a code of conduct to Github

- updated qutip.org news section and developers 

Notebooks:

- added Schrödinger cats time evolution notebook using single trajectories in mcsolve (**by Fabrizio Minganti**)

- added notebook of quantum tomography through maximum likelihood method on Wigner functions  (**by Shahnawaz Ahmed**)

- added development notebooks for the QObjEvo class, mcsolve and the stochastic solvers

Bug Fixes
---------

QuTiP:
- Fixed bug that made QuTiP incompatible with SciPy 1.3.
- `quite.cite()` is improved
- added `matplotlib` as optional dependency and updated `numpy` and `scipy` requirements
- fixed matrix generating coherent spin states in `qutip.piqs` to include complex coefficients

Documentation:
- Added User Guide example for `stochastic` solvers
- Added Floquet functions to API documentation
- Updated link to the Bloch sphere video decay 
- Added a short introduction to the new quantum Hellinger distance

Notebooks:
- Fixed bug that prevented notebooks to run on My Binder
- Updated user guide example of `wigner_cmap`

**Comment by ajgpitch** [comment]
Thanks @nathanshammah for the changelog proposal.
Few comments:
we should include Paul Nation in list of current developers. He is still active as far as I know
we should not include improvements to the website

**Comment by ajgpitch** [comment]
We need to include Franco in the the `qutip.about()`. I'll make a PR on this now

**Comment by ajgpitch** [comment]
The merge conflicts will need to be resolved

**Comment by nathanshammah** [comment]
Sure

**Comment by nathanshammah** [comment]
Should this be merged?

**Comment by Ericgig** [comment]
@nathanshammah 
Yes, there are still some part that don't build properly but the last documentation was build on this PR.

**Comment by nathanshammah** [comment]
I do not manage to solve the conflicts of the changelog

**Pull request merged**
