### PR TITLE
WIP:Documentation from scratch

### PR DESCRIPTION
**Pull request by quantshah**
This is a complete re-rendering of the basic documentation from scratch. This is done with the latest tools:

* sphinx v1.8.4
* sphinx_rtd_theme v0.4.3
* numpydoc v0.8.0

and the additional plugin sphinxcontrib-bibtex allows us to have bibtex (.bib) files and cite them from there. I thought that this could come in handy later if people start publishing their methods with QuTiP as tutorials and would like to simply add their (.bib) files and not worry about writing them again.

The next parts would be to add the existing QuTiP docs/tutorials in a way where we do not need to depend on ipython as it has been creating some issues. Personally, the less we depend on external stuff the better. But this bibliography tool seems to be very useful. 

Finally, I will add the warning "This is an older version of QuTiP. Please install the latest version and check out the documents here" which I showed in #2 

@ajgpitch @nathanshammah If you have suggestions along the way, I would be happy to include them as I will for sure re-write many parts of the code. Also, we could let this porting be a potential PR for Google Summer of Code. Essentially someone would have to read the old tutorials and copy-paste them here once I successfully generate one tutorial without running IPython.

### CODE REVIEW

**Comment by quantshah** [comment]
Another important task would be to add the `cannonical_url` tag so that Google's indexing always point to the latest version of the docs.

**Comment by ajgpitch** [comment]
This seems like a really great idea. Thanks @quantshah for starting this

**Comment by nathanshammah** [comment]
This seems interesting: https://github.com/semantic-release/semantic-release

**Comment by nathanshammah** [comment]
This PR has been on WIP for over a year and has several conflicts. The use of the bib extension I think it will require to rename the files with numbers, as the bib tool parses them alphabetically, not in the order they are given. 
Sphinx has gone up to v4. 

I think that manu good things are contained in this PR, but it may be best to start afresh.

**Comment by nathanshammah** [comment]
I will close this for the time being.

**Pull request closed without merging**
