### PR TITLE
update from control pulse PR

### PR DESCRIPTION
**Pull request by BoxiLi**
Update from https://github.com/qutip/qutip/pull/1155.

I successfully rendered the doc by deleting some other files in the user guide. So the qip part and the gallery part should be fine. But there are still tons of old issues... They are mainly caused by wrong code in ipython code embedding. Use python embedding can solve it but needs some work...

### CODE REVIEW

**Comment by nathanshammah** [comment]
How can we rebase this against my PR #97 branch?

Can you push it against it too?

Or otherwise I should do something like this
https://stackoverflow.com/questions/17967650/selectively-importing-other-peoples-pull-requests-in-your-own-github-fork

**Comment by BoxiLi** [comment]
Sure, I can try

**Comment by nathanshammah** [comment]
Ok maybe there is something easier: I will rebase both your and my PR to a new remote branch and merge first mine and then yours.

**Comment by BoxiLi** [comment]
OK, I actually just finished rebase, shall I push? Or you have solved it?

**Comment by BoxiLi** [comment]
I can handle the conflicts

**Pull request merged**
