### PR TITLE
updating improvements for 4.3 release

### PR DESCRIPTION
**Pull request by sahmed95**
Adding the improvements for 4.3 release.

### CODE REVIEW

**Comment by sahmed95** [comment]
@ajgpitch I am going to add the PIQS notebooks, documentation and make a 4.3 release. Please merge if this seems okay.

**Comment by ajgpitch** [comment]
I snuck in my unitary op evo

@sahmed95 Could you maybe look through the closed PRs and update the Bug Fixes section pls

**Comment by sahmed95** [comment]
Yes I was about to do so but I didn't know how detailed this should be so
only added what seemed to be major. I will do so and then merge this if
it's okay.

**Comment by ajgpitch** [comment]
Just one liners taken from the bug fix PRs. If anyone wants to know more they can look at the github.
Ignore any of the fixes we did to fix things that were caused by changes in other libraries. Just include things that were actual bugs in qutip.
Merge when you think it's ready

**Comment by ajgpitch** [comment]
Good work
Thanks

**Comment by sahmed95** [comment]
Thanks. We have the 4.3 release and I also have updated docs with the new piqs and scattering stuff. I will make the other changes tomorrow and make a pip release. This time it was less troubling.

**Comment by ajgpitch** [comment]
Excellent news. It is supposed to be as smooth as this :)

**Pull request merged**
