### PR TITLE
Create development section containing development ideas and the roadmap.

### PR DESCRIPTION
**Pull request by hodgestar**
The roadmap was already present in Markdown, but I migrated it to ReStructured Text.

The project ideas are from https://github.com/qutip/qutip/wiki/Google-Summer-of-Code-2021.

I haven't added the TensorFlow data backend proposal yet -- this PR is meant to bring the existing things together and translate them to Sphinx documentation without any changes. I'll add the TF backend proposal in a follow up PR.

### CODE REVIEW

**Comment by hodgestar** [comment]
I probably pinged too many reviewers, so feel free to skip if you are short on time or don't have opinions about how the development section of the docs should ook.

**Comment by ajgpitch** [comment]
This goes beyond what we (I) were thinking. It has much potential.
It also fulfils the initial objective of having some ideas documents to link to.
Hence I will merge now, and we can continue to discuss how we go about presenting developer related information

**Comment by nathanshammah** [comment]
Hi @hodgestar, my review would have been that markdown looks slightly better than .rst for this purpose because it can be read from github.com directly, and for this kind of documents it would be preferable, in my opinion, as editing (i.e. contributing) the file that one is reading is much more natural then reading it on the website, going to this github repo, and edit it with RST. 

More inconvenient though is that this way, updates are tied to qutip(-doc) release, am I understanding right? So the file does not show up properly (on qutip.org) until the next release. If it were a Markdown file, it could be read anytime, and then the updates could be part of the docs when they are released. 

I would suggest changing the conf.py file to include files in markdown (one option is `m2r`, but there are others, including using MyST parsers like [MystNB](https://myst-nb.readthedocs.io/en/latest/use/markdown.html)).

Besides the form of content, should we update the page at https://github.com/qutip/qutip/wiki/Google-Summer-of-Code-2021 or keep the project ideas there?

**Comment by hodgestar** [comment]
@nathanshammah Thanks for looking!

We should update the wiki page to link to the ideas .rst files. Note that I still have to add the ideas file for the tensorflow data backend.

Regarding Markdown: My thought was to make these pages properly part of the Sphinx documentation, and then to automate the building of the documentation so that updating the docs is no longer an issue. Alex and I checked and the idea .rst pages actually look pretty good in GitHub at the moment because they don't use any Sphinx-specific markup.

MystNB looks pretty cool, but I'd like to avoid multiple formats if we can and head directly towards the goal of automated builds without too many detours if we can (maybe we will use MystNB for other things).

Shout if you find any specific issues that you consider blockers, and if we don't find another way around them I'll see if I can bring back Markdown as a short term solution.

Sound good?

**Comment by nathanshammah** [comment]
Thanks for the reply @hodgestar. 

Rst files only partially render in Github.com, e.g., TOC and links do not work: https://github.com/qutip/qutip-doc/blob/master/development/ideas.rst
gh-qutip-doc-screenshot
.
So, right now, these ideas are very hard to find. I agree that having a `/latest/` doc version like with read the docs in the back-end would be a great thing. 
Since this change requires more steps and decisions for the migration, I propose to keep up to date for 2021 GSoC the QuTiP Wiki page, which is also right now linked on NumFOCUS GitHub repo about GSoC 2021 and in the News section on the QuTiP website. 

I still think that, whatever tool we'll use to build the documentation, using markdown is a bit more modern, although limited. Myst has the advantage that one can use either format plus .myst, to include things. I agree that sticking to one would be optimal and we have the legacy of the rst structure in the QuTiP documentation. 

Another thing to keep in mind is that we want these ideas page to be as easily editable and contributed to as possible. My impression is that markdown may be a lower entry barrier (e.g., for professor etc.) than other options, although both rst and markdown are not WYSIWYG.

**Comment by hodgestar** [comment]
> Rst files only partially render in Github.com, e.g., TOC and links do not work: https://github.com/qutip/qutip-doc/blob/master/development/ideas.rst

I know. :)

> Since this change requires more steps and decisions for the migration, I propose to keep up to date for 2021 GSoC the QuTiP Wiki page, which is also right now linked on NumFOCUS GitHub repo about GSoC 2021 and in the News section on the QuTiP website.

My understanding was that keeping the GSoC wiki page and linking directly to the individual proposal .rst documents on GitHub was the plan all along, so +1 from me. :)

**Pull request merged**
